# Generated by Django 4.2.1 on 2023-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='Password')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('ref_fabricante', models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia fabricante')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('caracteristica1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Caracteristica 1')),
                ('caracteristica2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Caracteristica 2')),
                ('familia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Familia')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca')),
                ('u_entrega', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad de entrega')),
                ('stock_min', models.IntegerField(blank=True, null=True, verbose_name='Stock minimo')),
                ('stock_actual', models.IntegerField(blank=True, null=True, verbose_name='Stock actual')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('albaran', models.CharField(blank=True, max_length=30, null=True, verbose_name='Albaran')),
                ('factura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Factura')),
                ('proveedor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Proveedor')),
                ('quien_entrega', models.CharField(blank=True, max_length=30, null=True, verbose_name='Quien entrega')),
                ('quien_recibe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Quien recibe')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='Password')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('tipo_usuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de usuario')),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
